### ISSUE TITLE
catch PCH errors with informative message

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanr#382] opened 2020-12-03 00:21 UTC
**Is your feature request related to a problem? Please describe.**

Yes.  I'm getting a PCH error:

```
> mod <- cmdstan_model('hetero-poststrat.stan')
Compiling Stan program...
error: PCH file uses an older PCH format that is no longer supported
1 error generated.
make: *** [/var/folders/zx/xndqhdss76gf03z8pyrpvdf00000gn/T/Rtmpd4mZSa/model-678c2118a9f8] Error 1
Error: An error occured during compilation! See the message above for more information.
```

Hint: that's from incompatible precompiled headers in C++.  The solution seems to be to call:

```
> rebuild_cmdstan()
```

(also, one function suffixes `cmdstan` while the other prefixes it)

**Describe the solution you'd like**

A way to catch this error coming back from C++ and recommend to the user that they call `rebuild_cmdstan()`.  I only figured this out because @mitzimorris was helping me with the install.

**Describe alternatives you've considered**

Reverting to RStan until installation kinks with CmdStanR are worked out.

**Comment by jgabry** [comment] 2020-12-03 02:45
I think this is a duplicate of #321, but yeah that's an annoying error. We definitely want to catch this and give the user an informative message. Here's @rok-cesnovar's comment https://github.com/stan-dev/cmdstanr/issues/321#issuecomment-715786086: 

> This is an issue that pops up on macOS sometimes when xcode upgrades. I think it happens often enough that we should try to catch this error message and signal to the user that rebuild_cmdstan() is the solution. Weirdly this does not pop up on Linux if I upgrade the clang compiler.I am going to reopen this and we can close this once we have a way to suggest to the user to rebuild cmdstan.

@mitzimorris Does CmdStanPy already catch this error and rebuild? I would think this would affect both interfaces the same since this error isn't coming from CmdStanR itself. We can probably use the same (or almost the same) solution. 

> (also, one function suffixes `cmdstan` while the other prefixes it)

In the first case you're creating a cmdstan model, in the second you're rebuilding cmdstan, so the function names have the words in that same order, which sounds more natural and we preferred at the time. But I'd be fine changing it if @rok-cesnovar and @mitzimorris are (we're also trying to use the same names as CmdStanPy). We have functions `rebuild_cmdstan`, `install_cmdstan`, `cmdstan_path`, cmdstan_version`, `cmdstan_model`, maybe others I'm forgetting.  To be honest, those names are all what seem the most natural to me for what they describe, but I don't feel too strongly about it so I'm happy with prioritizing consistency of prefix/suffix. 

> I only figured this out because @mitzimorris was helping me with the install.

Thankfully if you didn't have @mitzimorris you also could have found it (and the solution) in the open issue in the cmdstanr issue tracker (if you go to "issues" and put PCH in the search bar it will be the only thing that comes up other than your issue). I'm not trying to be snarky (I promise), I just want to point out that you said you "only figured this out" because of @mitzimorris but there were other simple ways for someone like you who knows github to find it. I completely agree we should catch this error so the user doesn't have to figure it out and not all users know their way around github, but it's really not nearly as impossible to find without the help of an insider as you made it sound.

**Comment by jgabry** [comment] 2020-12-03 02:48
I found this: https://github.com/stan-dev/cmdstanpy/issues/108 so maybe it's different in CmdStanPy but I can't quite tell because my Python knowledge is pretty basic

**Comment by jgabry** [comment] 2020-12-03 05:08
> Reverting to RStan until installation kinks with CmdStanR are worked out.

Most users I've interacted with have had an easier time with CmdStanR and, as a developer on both packages I would say RStan actually has more kinks at this point. But you (and the people you were helping recently) definitely ran into  several of the kinks left to resolve in CmdStanR so I understand your frustration. We're still working on finding and resolving all the possible issues.

**Comment by mitzimorris** [comment] 2020-12-03 05:40
currently CmdStanPy doesn't catch this error, nor does it have a "rebuild_cmdstan()" function, which it probably should.

I'm not sure what was behind  https://github.com/stan-dev/cmdstanpy/issues/108 - I don't think it was a PCH problem.

**Comment by rok-cesnovar** [comment] 2020-12-03 17:20
I think the only thing we can do here in cmdstanr is catching this error message in stderr and suggest rebuilding to the user. 

The actual fix will need to come in cmdstan. There were no changes to the precompiled headers for clang for at least 4-5 versions so I am not sure what changed with macOS and XCode. 

On Linux, I tried downgrading clang++ then building a model, updating clang++ and building the same model or another model and everything went smoothly. So it must be a macOS XCode thing.

**Comment by jgabry** [comment] 2020-12-03 18:44
I'm going to close this since it's a duplicate of #321. I don't think we need two open issues. 

> I think the only thing we can do here in cmdstanr is catching this error message in stderr and suggest rebuilding to the user.

Yeah I think that's the only thing we can do, but that would be good.

**Closed by jgabry** 2020-12-03 18:44 UTC
Labels: feature

**Comment by jgabry** [comment] 2020-12-03 19:16
Actually there's potentially a second issue here about the prefix/suffix use of cmdstan in function names, which @bob-carpenter mentioned in passing. Since that's a separate topic @bob-carpenter if you want to open a separate issue about it that would be great. Thanks!
