### ISSUE TITLE
Get appveyor CI for windows working

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanr#80] opened 2019-11-12 21:49 UTC
@rok-cesnovar I added an `.appveyor.yml` config file so we can try continuous integration on windows via appveyor (in addition to linux on travis). It's working (running on appveyor) but errorring when running some of the unit tests (https://ci.appveyor.com/project/jgabry/cmdstanr/history). 

I also started a branch `appveyor-ci-windows` for if we need to play around with changing things in the package (other than just the `.appveyor.yml` file) to get it to work. 

Most of the `.appveyor.yml` file is set to the defaults recommended in https://github.com/krlmlr/r-appveyor#readme, except I added to `build_script:` the line 

```r
  - cmd: bash inst/make_cmdstan.sh -j2 -w
```

which seems to at least run but may not be successful. 

One issue seems to be that the default paths used on appveyor may be different than what we're expecting in various functions (e.g., `make_cmdstan.sh`, `set_cmdstan_path()`). But I'm having a bit of trouble figuring out what's going on since Windows confuses the hell out of me!

The nice thing about appveyor though is that you can download the failure logs by going to the "Artifacts" tab when on the page for a particular build.

**Comment by jgabry** [comment] 2019-11-12 22:45
Also just in case we need to set paths differently on appveyor I added a function in a `helper-` file in the tests directory that branches on whether we're on appveyor or not: 

https://github.com/stan-dev/cmdstanr/blob/ce2cc6f3794ae4a8608d14ff800fbbbdae1e594f/tests/testthat/helper-envvars-and-paths.R#L14-L20

It does the same thing either way right now but we can change it if we need to.

**Comment by rok-cesnovar** [comment] 2019-11-13 18:54
There were some tests failing on Windows even locally. I pushed the fixes on the appveyor branch. Does that trigger any tests to check if there is any other error left now?

**Comment by jgabry** [comment] 2019-11-13 19:00
Thanks. Do you mean does appveyor automatically test again when you make a commit? It should. Are you able to access https://ci.appveyor.com/project/jgabry/cmdstanr/history?

**Comment by rok-cesnovar** [comment] 2019-11-13 19:17
Yes I can access that. Thanks!

**Comment by jgabry** [comment] 2019-11-13 19:49
You can also download `failure.zip` from https://ci.appveyor.com/project/jgabry/cmdstanr/builds/28837393/artifacts. If you unzip it the you get a directory `cmdstanr.Rcheck`. There's probably only one file in there that's useful (maybe):  `cmdstanr.Rcheck/tests/testthat.Rout.fail`.

**Comment by rok-cesnovar** [comment] 2019-11-13 19:54
Thanks. I can see that it fails with "CmdStan path has not been set yet. See ?set_cmdstan_path.".

cmdstan actually gets installed to C:/MinGW/msys/1.0/ so that is where I set HOME to. Crossing fingers now that that helps :)

**Comment by jgabry** [comment] 2019-11-13 20:05
I just pushed a commit to that branch too (so you might want to pull), but what I changed is orthogonal to the appveyor/windows issue shouldn't affect anything (just cleaning up a few old things in testthat.R that shouldn't be necessary anymore)

**Comment by jgabry** [comment] 2019-11-13 20:06
> cmdstan actually gets installed to C:/MinGW/msys/1.0/ so that is where I set HOME to. Crossing fingers now that that helps :)

Worth a try!

**Comment by jgabry** [comment] 2019-11-13 20:15
Another thing I just noticed is that on appveyor there's an info message when building cmdstan: 

```
bash inst/make_cmdstan.sh -j2 -w
...
* Building CmdStan binaries.
INFO: Could not find files for the given pattern(s).
...
```

link to lines in appveyor log: https://ci.appveyor.com/project/jgabry/cmdstanr/builds/28838920#L679

I don't get that message when I install locally. Any idea where that comes from and if that's a problem?

**Comment by rok-cesnovar** [comment] 2019-11-13 20:56
I get the same "INFO: Could not find files for the given pattern(s)." message on Windows so that is fine I guess. 

The strange thing are the \\ and \. at the end of files when compiling.

`Actual value: "\[1\] "Running mingw32-make\.exe \\\\\\\\"                                                                                       \\n\[2\] "  \\\\"C:/MinGW/msys/1\.0/\.cmdstanr/cmdstan/examples/bernoulli/bernoulli\.exe\\\\""                                        \\n\[3\] "mingw32-make\.exe: Nothing to be done for 'C:/MinGW/msys/1\.0/\.cmdstanr/cmdstan/examples/bernoulli/bernoulli\.exe'\.\\\\r""`

I dont see anything wrong in the paths in this case tho: 
```
> test_check("cmdstanr")
Running mingw32-make.exe \
  "C:/projects/cmdstanr/cmdstanr.Rcheck/tests/testthat/resources/stan/logistic.exe"
mingw32-make.exe: *** No rule to make target 'C:/projects/cmdstanr/cmdstanr.Rcheck/tests/testthat/resources/stan/logistic.exe'.  Stop.
```
I have a few more ideas will do a few more rounds of stabbing in the dark :)

**Comment by jgabry** [comment] 2019-11-13 22:03
Thanks for trying!

**Comment by jgabry** [comment] 2019-11-14 01:58
@rok-cesnovar just a heads up I did a bunch of work on #68 reorganizing test files so I went ahead and updatged the appveyor branch too to keep it up to date.

**Comment by jgabry** [comment] 2019-11-15 03:46
@rok-cesnovar Thanks again for trying to figure this out. I didn’t realize it would be so annoying to get working, sorry!

**Comment by rok-cesnovar** [comment] 2019-11-15 06:48
It seems as if its not respecting the wd argument. make spits out nothin to do for x, which means that it does find the exe file but not the make rule. As if its not being called in the cmdstan folder. Otherwise it would say "is up to date". Very bizzare. Will spin up a windows 2012 server instance later today to see if its something related to that win version.

**Comment by rok-cesnovar** [comment] 2019-11-15 21:34
This is a tough one. I am able to run tests manually on Windows server 2019 and 2016, wasn't able to make it work on 2012. But appveyor on 2016 or 2019 still doesn't give in. 

I am going to try and make custom scripts that would not install all these tools, just those we really need. I have a gut feeling the issue is that one of the build tools used is not from RTools and then things mix up and you get a headache :)

**Comment by jgabry** [comment] 2019-11-15 22:33
Thanks @rok-cesnovar, sounds like a serious headache indeed! 

@ahartikainen @mitzimorris it looks like you have an appveyor.yml file for cmdstanpy (and that it’s installing rtools, although maybe a different one than we are). Did you have any of these issues? Also I can’t seem to find the appveyor logs for cmdstanpy online. Is there a url?

**Comment by ahartikainen** [comment] 2019-11-15 23:58
https://ci.appveyor.com/project/ahartikainen/cmdstanpy-kkwu4

I would not touch msys on appveyor if not really needed.

What toolchain are you using?

**Comment by rok-cesnovar** [comment] 2019-11-16 16:24
We are using Rtools and the g++ that comes with it.

Its not really a toolchain problem now, the external processes execution, specifically make, is behaving weirdly.

**Comment by ahartikainen** [comment] 2019-11-16 19:34
So, if you ran make commands in cmdline (in appveyor) everything works? But calling from R make fails?

Just making sure you call `mingw32-make`?

**Comment by rok-cesnovar** [comment] 2019-11-16 19:56
Yeah, I can build and run cmdstan in cmdline. The thing is that everything works on Windows otherwise for me locally, I can run all tests in the package, run models, etc. I mostly do stuff through RStudio tho. 

So I think it's a PowerShell/cmd confusion I guess. Try to be more consistent now.

**Comment by rok-cesnovar** [comment] 2019-11-16 22:15
Ok, its finally working: https://ci.appveyor.com/project/jgabry/cmdstanr/builds/28910508

A new version is here https://github.com/stan-dev/cmdstanr/tree/appveyor-win-pt2
Will clean this up tomorrow and make a PR.

**Comment by jgabry** [comment] 2019-11-16 22:41
Awesome!!

**Closed** 2019-11-17 21:16 UTC
Labels: internal-code, windows
