### ISSUE TITLE
compilation of Stan model functions do not work

### ISSUE THREAD

**Issue by wds15** [stan-dev/cmdstanr#837] opened 2023-08-25 09:30 UTC
**Describe the bug**
I get this error when trying to compile Stan model functions:

<img width="567" alt="image" src="https://github.com/stan-dev/cmdstanr/assets/12070126/dbac5c58-aabc-435b-8f70-af7c806574c0">

**To Reproduce**
see above...should be the case for any model

**Expected behavior**
Should just work ok...workaround:

<img width="474" alt="image" src="https://github.com/stan-dev/cmdstanr/assets/12070126/c9794354-7084-42eb-8858-c215bebd912b">

So it looks as if the boolean flag "external" does not get initialised in the functions environment which makes things break.

**Operating system**
macOS

**CmdStanR version number**
0.6.0

**Additional context**

**Comment by wds15** [comment] 2023-08-25 09:55
I should probably add that this was with cmdstan 2.33.0-rc1 .

**Comment by rok-cesnovar** [comment] 2023-08-25 10:32
This is with the released version, right? Have you tried the development version from Github?

**Comment by wds15** [comment] 2023-08-25 11:12
It's the release one, yes...will try with GitHub and report back, sure.

**Comment by andrjohns** [comment] 2023-08-25 12:05
Duplicate of #830 and #819, resolved by #831

Closing for now, feel free to reopen if you still have issues with the github version

**Closed by andrjohns** 2023-08-25 12:05 UTC
Labels: bug

**Comment by andrjohns** [comment] 2023-08-25 12:07
@rok-cesnovar @jgabry should we do a minor release soon with these bugfixes in?

**Comment by rok-cesnovar** [comment] 2023-08-25 12:20
Yeah, I am all for it. We don't need to rebuild the websites, just put it in r-packages repo.

**Comment by andrjohns** [comment] 2023-08-25 12:42
Sounds like a plan, I'll build the new binaries and put together some quick release notes later today

**Comment by wds15** [comment] 2023-08-25 13:08
With the GitHub version things work just fine. Sorry for reporting again... and a 0.6.1 would be fantastic!

**Comment by jgabry** [comment] 2023-08-25 15:30
> Sounds like a plan, I'll build the new binaries and put together some quick release notes later today

@andrjohns i think for cmdstanr we should just update the source and not have binaries because they don’t really provide any advantage (unlike for RStan). That way we only have to remember to update one thing. In the past at one point we forgot to update the binaries and sometimes it would install an old binary even if the source was later (I didn’t think it should do that but I ran into that a few times)

**Comment by jgabry** [comment] 2023-08-25 15:32
> > Sounds like a plan, I'll build the new binaries and put together some quick release notes later today
> 
> @andrjohns i think for cmdstanr we should just update the source and not have binaries because they don’t really provide any advantage (unlike for RStan). That way we only have to remember to update one thing. In the past at one point we forgot to update the binaries and sometimes it would install an old binary even if the source was later (I didn’t think it should do that but I ran into that a few times)

When I did 0.6.0 I had to remove binaries because they were interfering with installing the more recent source for some reason when installing from the drat repo

**Comment by jgabry** [comment] 2023-08-25 15:38
I have some time now so I can go ahead and tag the release and add the source to r-packages
