### ISSUE TITLE
get_stan_cflags behaves poorly under recursive `make`

### ISSUE THREAD

**Issue by bbolker** [stan-dev/cmdstanr#770] opened 2023-05-27 18:54 UTC
(This seems to belong here, but arguably it could belong on the `brms` issues list. I'd be happy to post it there instead if advised.)

As noted [here](https://myprogrammingnotes.com/entering-directory-leaving-directory-messages-make-output.html), when `make` is called recursively it automatically prints

```
make[N]: Entering directory ...
make[N]: Leaving directory ...
```
messages (where `N` is the stack level).

According to [the documentation](https://www.gnu.org/software/automake/manual/html_node/Tricks-For-Silencing-Make.html),  these messages can be silenced by calling `make -s`.   [This commit](https://github.com/bbolker/cmdstanr/commit/5e77e1988f07f0911e4a3d8840a2b76fb5c8b1e1) makes that change; I'd be happy to submit a PR (I can't see how it would break anything else - the `-s` flag is supposed to be POSIX-portable - but you never know ...)

More details below as to what these messages break and why ...

----

If I run 

```
Rscript -e "sink('test2.Rout'); cat(cmdstanr:::get_cmdstan_flags('STANCFLAGS'), '\n')"
```

in the shell I get an empty `STANCFLAGS` (i.e., `test2.Rout` has only a newline in it).

If I write a Makefile with the rule

```
test.Rout:
	Rscript -e "sink('test2.Rout'); cat(cmdstanr:::get_cmdstan_flags('STANCFLAGS'), '\n')"
```

then `test2.Rout` contains this:

```
make[1]: Entering directory '/home/bolker/.cmdstan/cmdstan-2.32.2'STANCFLAGS =make[1]: Leaving directory '/home/bolker/.cmdstan/cmdstan-2.32.2
```

Downstream, this leads to errors of the following form when I try to run `brms` (with the `cmdstanr` backend, of course).

```
Error in `if (stancflags_local != "") ...`:
! the condition has length > 1
Backtrace:
  1. global test_prior(b_prior)
  4. brms::brm(...)
  5. brms::do_call(compile_model, compile_args)
  6. brms:::eval2(call, envir = args, enclos = envir)
  7. base::eval(expr, envir, ...)
     ...
 17. base::eval(expr, envir, ...)
 18. cmdstanr (local) .fun(stan_file = .x1)
 19. CmdStanModel$new(...)
 20. cmdstanr (local) initialize(...)
 21. self$compile(...)
                                                                                                         
Execution halted
```

**Comment by andrjohns** [comment] 2023-05-27 19:39
The length > 1 error can be fixed with [this commit](https://github.com/stan-dev/cmdstanr/compare/master...stancflags-check)

But I can't reproduce the directory change output that you've mentioned.

I created a Makefile with the content:
```makefile
test.Rout:
	Rscript -e "sink('test2.Rout'); cat(cmdstanr:::get_cmdstan_flags('STANCFLAGS'), '\n')"

testing:
	$(MAKE) test.Rout

```

Running gives output:
```bash
andrew@Andrews-MacBook-Air tmp % make testing
/Library/Developer/CommandLineTools/usr/bin/make test.Rout
Rscript -e "sink('test2.Rout'); cat(cmdstanr:::get_cmdstan_flags('STANCFLAGS'), '\n')"

# File is empty
andrew@Andrews-MacBook-Air tmp % cat test2.Rout 
 ```

Is there a step I'm missing to reproduce?

**Comment by bbolker** [comment] 2023-05-27 20:09
I'm wondering if different versions of `make` are in use (and variously do or don't spit out these entering/leaving messages) ... ??  I have

```
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

The info linked above looks like it's being run on Windows. I would be surprised but not shocked if it some versions of `make` available on MacOS had different default behaviour about printing these messages ...?

**Comment by andrjohns** [comment] 2023-05-27 20:23
Hm might be the case, looks like the MacOS make is a bit old:
```
andrew@Andrews-MacBook-Air ~ % make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

I'll try with a newer version or a docker container

**Comment by andrjohns** [comment] 2023-05-27 20:26
Interesting, with a newer make the directory changes are printed to the shell but not captured in the output:
```
andrew@Andrews-MacBook-Air tmp % gmake -v
GNU Make 4.4.1
Built for aarch64-apple-darwin22.3.0
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

andrew@Andrews-MacBook-Air tmp % gmake testing
gmake test.Rout
gmake[1]: Entering directory '/Users/andrew/tmp'
Rscript -e "sink('test2.Rout'); cat(cmdstanr:::get_cmdstan_flags('STANCFLAGS'), '\n')"
gmake[1]: Leaving directory '/Users/andrew/tmp'

andrew@Andrews-MacBook-Air tmp % cat test2.Rout 
 
```

I'll try with a docker container tomorrow and see if it's an OS-specific thing

**Comment by bbolker** [comment] 2023-05-27 20:46
Maybe there are differences in how different output streams are handled/captured in `sink()`?

**Comment by tjmahr** [comment] 2023-09-19 18:57
This error bit me today, and it appears to be an easy fix. Will you create the pull request @andrjohns?

Here is a minimal example without brms.

This is the contents of Makefile:

```
.PHONY: test

test:
	Rscript --version
	Rscript --vanilla -e "                            \
	  packageVersion('cmdstanr');                     \
	  cmdstanr::cmdstan_version();                    \
	  cmdstanr::check_cmdstan_toolchain();            \
	  cmdstanr:::get_cmdstan_flags('STANCFLAGS');     \
	  try(cmdstanr::cmdstanr_example(quiet = FALSE)); \
	"
```

Here is the reproducible reprex, produced by running `reprex::reprex(wd = ".", std_out_err = TRUE)`.

``` r
writeLines(readLines("Makefile"))
#> .PHONY: test
#> 
#> test:
#>  Rscript --version
#>  Rscript --vanilla -e "                            \
#>    packageVersion('cmdstanr');                     \
#>    cmdstanr::cmdstan_version();                    \
#>    cmdstanr::check_cmdstan_toolchain();            \
#>    cmdstanr:::get_cmdstan_flags('STANCFLAGS');     \
#>    try(cmdstanr::cmdstanr_example(quiet = FALSE)); \
#>  "
system("make")
#> [1] 0
```

<sup>Created on 2023-09-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Standard output and standard error
</summary>

``` sh
Rscript --version
Rscript (R) version 4.3.1 (2023-06-16)
Rscript --vanilla -e "                            \
  packageVersion('cmdstanr');                     \
  cmdstanr::cmdstan_version();                    \
  cmdstanr::check_cmdstan_toolchain();            \
  cmdstanr:::get_cmdstan_flags('STANCFLAGS');     \
  try(cmdstanr::cmdstanr_example(quiet = FALSE)); \
"
[1] '0.6.1'
[1] "2.33.1"
The C++ toolchain required for CmdStan is setup properly!
[1] "make[1]:"                                                    
[2] "Entering"                                                    
[3] "directory"                                                   
[4] "'/c/Users/trist/Documents/.cmdstan/cmdstan-2.33.1'STANCFLAGS"
[5] "=make[1]:"                                                   
[6] "Leaving"                                                     
[7] "directory"                                                   
[8] "'/c/Users/trist/Documents/.cmdstan/cmdstan-2.33.1'"          
Error in if (stancflags_local != "") { : the condition has length > 1
```

</details>

**Comment by pearsonca** [comment] 2023-11-21 09:54
Also just got bit by this.

**Closed** 2023-11-29 15:29 UTC
Labels: bug
