### ISSUE TITLE
discussion on the help interface

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#363] opened 2020-11-22 12:21 UTC
Despite being an R user for 15 years, I have difficulty working with how cmdstanr is set up with the standard R help pages. Very common practice for when you don't know the arguments to a function `fun` is to simply type `?fun` in the console, bringing up the help page. But for a compiled model `mod`, when I want to run the sample function but want to remind myself of the available arguments, running `?mod$sample` brings up nothing. Similarly, in the RStudio IDE, typing `mod$sample(` *does* start giving tooltip hints for arguments, *but for the wrong function* (i.e. for `base::sample`). Yes, ultimately the answer is RTFM, but given how engrained expectations will be from users to be able to use the help system in this standard way, I think we need to figure out how to enable it. Surely this is a solved thing for R6 and we just need to implement those solutions?

**Comment by rok-cesnovar** [comment] 2020-11-22 12:26
I think the answer here is solving https://github.com/stan-dev/cmdstanr/issues/81

Agree with your points otherwise, it's not ideal for docs right now.

**Comment by rok-cesnovar** [comment] 2020-11-24 11:09
Going to close this as once #81 is solved, this will be solved as well. That issue is still blocked by no roxygen support for R6 functions done via set().

For now ?CmdstanModel, ?CmdstanMCMC, etc will have to do.

**Closed by rok-cesnovar** 2020-11-24 11:09 UTC

**Comment by jgabry** [comment] 2020-11-24 17:48
Also related to #367. I need to check if they've improved roxygen2 support for R6 objects since they initially started supported them last year. At that time the support was insufficient for the complexity of CmdStanR's code base but maybe it's different now.

**Comment by jgabry** [comment] 2020-11-24 17:55
> Surely this is a solved thing for R6 and we just need to implement those solutions?

You would think so but unfortunately roxygen2's R6 support is pretty limited the last time I checked. I suppose we could change our code base to not define methods via $set() but really roxygen2 should support documentation of methods via $set() since that's a standard feature in R6.  Unfortunately it looks like the issue is still open and I don't see any recent activity: https://github.com/r-lib/roxygen2/issues/931
