### ISSUE TITLE
uninformative error message "Warning: Chain 1 finished unexpectedly!", when I refer to a non-existend index

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/cmdstanr#441] opened 2021-01-30 22:59 UTC
**Describe the bug**
When I use a wrong index in an array, I get "Warning: Chain 1 finished unexpectedly!" errors

**To Reproduce**
```
cat('
data {

}
parameters {
 real alpha;
}
transformed parameters {
 real beta[2];
  print(beta[3]);
}
model {
 target += normal_lpdf(0 | alpha, 1);
}
',file = "bad_index.stan")

m_bad <- cmdstan_model("./bad_index.stan")
f_mirror <- m_bad$sample(data=list(),chains =4, parallel_chains = 4, output_dir = "output")

```

**Expected behavior**
I would expect a more informative message

**Operating system**
Ubuntu 20.04.1

**CmdStanR version number**
0.3.0

**Additional context**

**Comment by rok-cesnovar** [comment] 2021-02-01 08:52
Hi Bruno, 

thanks for the report. This is somewhat related to #405. 

The problem is these errors are not reported to stderr in Cmdstan but rather stdout and we do not output everyhing on stdout as its a lots of traffic on stdout at the start. Will see if we can somehow let these prints though.

Whatver is printed to stderr is always passed to the user as there are no exceptions there.

**Comment by avehtari** [comment] 2021-02-03 13:10
I add that when running the same code in Emacs ESS and Rstudio, and if passed data doesnt't match with the data block declarations I get the appropriate informative error message visible in Emacs ESS but RStudio shows only that "finished unexpectedly" meassage.

**Comment by rok-cesnovar** [comment] 2021-03-12 11:03
This has been fixed in cmdstan (in stanc3 to be exact), now reporting a message like: 

```
Chain 1 Unrecoverable error evaluating the log probability at the initial value. 
Chain 1 Exception: array[uni, ...] index: accessing element out of range. index 3 out of range; expecting index to be between 1 and 2 (in '/tmp/RtmpPxdllW/model-85fe7ccb07ed.stan', line 10, column 2 to column 17) 
Chain 1 Exception: array[uni, ...] index: accessing element out of range. index 3 out of range; expecting index to be between 1 and 2 (in '/tmp/RtmpPxdllW/model-85fe7ccb07ed.stan', line 10, column 2 to column 17)
```

As there is not much else to do in cmdstanr, I will close this issue.

**Closed by rok-cesnovar** 2021-03-12 11:03 UTC
Labels: bug
