### ISSUE TITLE
Would it make sense to use .exe on all platforms?

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#334] opened 2020-11-02 15:32 UTC
Is there any reason `cmdstanr` works to ensure binaries on the different platforms have different names? So far as I understand, on mac/linux there's no detriment to adding the suffix '.exe' to the file name of a binary, so it seems like an unnecessary source of code complexity to nonetheless enforce the difference across platforms. Or is suffixing a unix binary with exe so counter-culture as to induce likely confusion?

**Comment by mitzimorris** [comment] 2020-11-02 17:11
> exe so counter-culture as to induce likely confusion?

most definitely the latter.

**Comment by rok-cesnovar** [comment] 2020-11-03 08:48
Good question. I personally would not mind this, but I was a Windows user up until maybe 6-7 years ago so I am accustomed to seeing the .exes :)

The problem is if we wanted to build `model.exe` on Unix we would have to either: 
- rename `model.stan` to `model.exe.stan` on Unix only
- rename the built executable file afterwards (again on Unix only)

So we get the same "complexity" just the other way around. 

The only proper way of doing this would be changing cmdstan makefiles. However if we changed that make model.stan produces model.exe on Unix system that break backward compatibility and would cause confusion there. So we are left with this distinction for Windows. 

Will close this, but feel free to reopen if anyone feels otherwise.

**Closed by rok-cesnovar** 2020-11-03 08:48 UTC
