### ISSUE TITLE
include file not found

### ISSUE THREAD

**Issue by copernican** [stan-dev/cmdstanr#687] opened 2022-08-08 15:28 UTC
**Describe the bug**
It appears that the handling of `#include` statements/`include_paths` may have changed from 0.5.2 to 0.5.3. With 0.5.3, the example from #680 gives this error:

```r
library(cmdstanr)
#> This is cmdstanr version 0.5.3
#> - CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
#> - CmdStan path: /home/sean_wilson/.cmdstan/cmdstan-2.30.1
#> - CmdStan version: 2.30.1

data_code <- "
  data {
    int N;
  }
  "
data_file <- write_stan_file(code = data_code, basename = "data.stan")

model_code <- "
  #include data.stan
  parameters {
    vector[N] y;
  }
  model {
    y ~ std_normal();
  }
  "

model_file <- write_stan_file(code = model_code)
mod <- cmdstan_model(model_file, include_paths = dirname(data_file))
#> Syntax error in '/tmp/Rtmp6K52UA/model-2f3e47a3b4af.stan', line 2, column 2, include error:
#>    -------------------------------------------------
#>      1:  
#>      2:    #include data.stan
#>            ^
#>      3:    parameters {
#>      4:      vector[N] y;
#>    -------------------------------------------------
#> 
#> Could not find include file data.stan in specified include paths.
#> make: *** [/tmp/Rtmp6K52UA/model-2f3e47a3b4af.hpp] Error 1
#> Error: An error occured during compilation! See the message above for more information.
```

Under 0.5.2, it compiles fine.
```r
library(cmdstanr)
#> This is cmdstanr version 0.5.2
#> - CmdStanR documentation and vignettes: mc-stan.org/cmdstanr
#> - CmdStan path: /home/sean_wilson/.cmdstan/cmdstan-2.30.1
#> - CmdStan version: 2.30.1

data_code <- "
  data {
    int N;
  }
  "
data_file <- write_stan_file(code = data_code, basename = "data.stan")

model_code <- "
  #include data.stan
  parameters {
    vector[N] y;
  }
  model {
    y ~ std_normal();
  }
  "

model_file <- write_stan_file(code = model_code)
mod <- cmdstan_model(model_file, include_paths = dirname(data_file))
mod$exe_file()
#> [1] "/tmp/Rtmpz2t7Q8/model_00252e81bad3382f6acdbe052a2f2912"
```

**Expected behavior**
The expected behavior is that the `#include` statement works as in 0.5.2.

**Operating system**
Ubuntu 18.04.6

**CmdStanR version number**
0.5.3

**Comment by ph-rast** [comment] 2022-10-11 22:20
I can confirm this issue on both Ubuntu 22.10 LTS  and a Mac Book M1 for cmdstanr version 0.5.3

**Comment by andrjohns** [comment] 2022-10-13 08:50
This appears to be resolved in the Github version, as I can't reproduce on an M1 Mac. Can you try installing the dev version:
```r
remotes::install_github("stan-dev/cmdstanr")
```

And trying again?

**Comment by copernican** [comment] 2022-10-13 13:21
I agree that the dev version works as expected. Thanks for following up.

**Closed** 2022-10-13 13:23 UTC
Labels: bug

**Comment by ph-rast** [comment] 2022-10-13 16:33
> This appears to be resolved in the Github version, as I can't reproduce on an M1 Mac. Can you try installing the dev version:
> 
> ```r
> remotes::install_github("stan-dev/cmdstanr")
> ```
> 
> And trying again?

All good - thanks!

**Comment by beansrowning** [comment] 2023-01-27 17:08
I'm not sure if the root cause of this issue was ever identified, but I can reproduce this issue on the most recent development version (b5d3a77) using @copernican's reprex above on Win 10 and Redhat Linux.

**Comment by andrjohns** [comment] 2023-01-27 19:31
I'm still not able to replicate this locally. Do you get the same error/warning if you use `cmdstan` directly (i.e., from the command line, not through `cmdstanr`) to compile the model?

**Comment by copernican** [comment] 2023-01-27 20:45
Interesting, it also seems to happen from the command line:

```sh
➜  cmdstan-2.30.1 pwd
/Users/sean_wilson/.cmdstan/cmdstan-2.30.1
➜  cmdstan-2.30.1 cat ~/data.stan
data {
  int N;
}
➜  cmdstan-2.30.1 cat ~/model.stan
#include data.stan
parameters {
  vector[N] y;
}
model {
  y ~ std_normal();
}
➜  cmdstan-2.30.1 make STANCFLAGS="--include-paths=~" ~/model

--- Translating Stan model to C++ code ---
bin/stanc --include-paths=~ --o=/Users/sean_wilson/model.hpp /Users/sean_wilson/model.stan
Syntax error in '/Users/sean_wilson/model.stan', line 1, column 0, include error:
   -------------------------------------------------
     1:  #include data.stan
         ^
     2:  parameters {
     3:    vector[N] y;
   -------------------------------------------------

Could not find include file data.stan in specified include paths.
make: *** [/Users/sean_wilson/model.hpp] Error 1
```

**Comment by beansrowning** [comment] 2023-01-27 21:08
> Interesting, it also seems to happen from the command line:
> 
> ```shell
> ➜  cmdstan-2.30.1 pwd
> /Users/sean_wilson/.cmdstan/cmdstan-2.30.1
> ➜  cmdstan-2.30.1 cat ~/data.stan
> data {
>   int N;
> }
> ➜  cmdstan-2.30.1 cat ~/model.stan
> #include data.stan
> parameters {
>   vector[N] y;
> }
> model {
>   y ~ std_normal();
> }
> ➜  cmdstan-2.30.1 make STANCFLAGS="--include-paths=~" ~/model
> 
> --- Translating Stan model to C++ code ---
> bin/stanc --include-paths=~ --o=/Users/sean_wilson/model.hpp /Users/sean_wilson/model.stan
> Syntax error in '/Users/sean_wilson/model.stan', line 1, column 0, include error:
>    -------------------------------------------------
>      1:  #include data.stan
>          ^
>      2:  parameters {
>      3:    vector[N] y;
>    -------------------------------------------------
> 
> Could not find include file data.stan in specified include paths.
> make: *** [/Users/sean_wilson/model.hpp] Error 1
> ```

Ditto. @andrjohns 

```sh
make STANCFLAGS="--include-paths=~/stan_test" ~/stan_test/model
--- Translating Stan model to C++ code ---
bin/stanc --include-paths=~/stan_test --o=/home/nfs/<xxxx>/stan_test/model.hpp /home/nfs/<xxxx>/stan_test/model.stan
Syntax error in '/home/nfs/<xxxx>/stan_test/model.stan', line 1, column 0, include error:
   -------------------------------------------------
     1:  #include data.stan
         ^
     2:  parameters {
     3:    vector[N] y;
   -------------------------------------------------

Could not find include file data.stan in specified include paths.
make: *** [make/program:50: /home/nfs/<xxxx>/stan_test/model.hpp] Error 1

bash-4.4$ g++ --version
g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10.1.0.1)
bash-4.4$ make --version
GNU Make 4.2.1
Built for x86_64-redhat-linux-gnu
```

**Comment by rok-cesnovar** [comment] 2023-01-27 21:18
Can you try replacing the tilde with the full path to the home folder?

**Comment by beansrowning** [comment] 2023-01-27 21:27
> Can you try replacing the tilde with the full path to the home folder?

Ah! Very astute. Looks like this has something to do with tilde expansion, then:

```
bash-4.4$ make STANCFLAGS="--include-paths=/home/nfs/<xxxx>/stan_test" /home/nfs/<xxxx>/stan_test/model 

--- Translating Stan model to C++ code ---
bin/stanc --include-paths=/home/nfs/<xxxx>/stan_test --o=/home/nfs/<xxxx>/stan_test/model.hpp /home/nfs/<xxxx>/stan_test/model.stan

--- Compiling, linking C++ code ---
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -Wno-ignored-attributes   -x c++ -o /home/nfs/<xxxx>/stan_test/model.o /home/nfs/<xxxx>/stan_test/model.hpp
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS                -Wl,-L,"/home/nfs/<xxxx>/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/home/nfs/<xxxx>/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb"      /home/nfs/<xxxx>/stan_test/model.o src/cmdstan/main.o        -Wl,-L,"/home/nfs/<xxxx>/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"/home/nfs/<xxxx>/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb"   stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a  stan/lib/stan_math/lib/tbb/libtbb.so.2 -o /home/nfs/<xxxx>/stan_test/model
rm -f /home/nfs/<xxxx>/stan_test/model.o
```

**Comment by beansrowning** [comment] 2023-01-27 21:44
I used the above script, so:

```r
model_file
# [1] "/opt/tmp/Rtmp64F3UO/model_00252e81bad3382f6acdbe052a2f2912.stan"
data_file
# [1] "/opt/tmp/Rtmp64F3UO/data.stan"
dirname(data_file)
# [1] "/opt/tmp/Rtmp64F3UO"

mod <- cmdstan_model(model_file, include_paths = dirname(data_file))
# Compiling Stan program...
# Syntax error in '/opt/tmp/Rtmp64F3UO/model_00252e81bad3382f6acdbe052a2f2912.stan', line 2, column 2, include error:
#   -------------------------------------------------
#     1:  
#     2:    #include data.stan
#           ^
#     3:    parameters {
#     4:      vector[N] y;
#   -------------------------------------------------
```

**Comment by copernican** [comment] 2023-01-27 21:47
In the original example, I used the `include_paths` argument:

```r
cmdstan_model(model_file, include_paths = dirname(data_file))
```

which evaluates to a temporary directory (which does not have a tilde):

```r
> dirname(data_file)
[1] "/tmp/Rtmpk6keCu"
```

**Comment by andrjohns** [comment] 2023-01-27 22:08
It looks like your `cmdstan` install is located on a network file share, do you experience the same behaviour with `cmdstanr` if your `cmdstan` install is located on your local computer?

**Comment by andrjohns** [comment] 2023-01-27 22:25
In a similar vein, are your R packages (namely `cmdstanr`) installed locally or on the network drive?

**Comment by copernican** [comment] 2023-01-27 22:29
1. On macOS 13.1 (so, everything installed locally), with CmdStan 2.31.0 and cmdstanr 0.5.3, the original example works as desired.
2. On Ubuntu 18.04.6 with everything installed on network shares, and the same versions of CmdStan and cmdstanr as the local example, I get the `#include` error in the original example.
3. Same setup as (2), but with CmdStan installed from GitHub, it works fine.

**Comment by beansrowning** [comment] 2023-01-30 16:21
> It looks like your cmdstan install is located on a network file share, do you experience the same behaviour with cmdstanr if your cmdstan install is located on your local computer?

Yeah, this is using a VM. I've installed it locally to a win 10 laptop and encountered the same issue using CRAN install and the latest from github with CmdStan 2.31.0

> In a similar vein, are your R packages (namely cmdstanr) installed locally or on the network drive?

On the redhat VM the packages are in NFS, but on Windows I have them installed locally (and not in a onedrive synced folder, either).

Maybe worth mentioning that on windows I have to override the default install path for cmdstan since my employer sets the `%HOME%` path to a OneDrive synced location rather than `C:/Users/<xx>/`. I use `set_cmdstan_path("C:/Users/<xx>/.cmdstan/")` and override `%HOME%` to `C:/Users/<xx>/`, since this seems to be referenced in some internal functions.

As I mentioned, the model *does* seem to compile even though the syntax error is echoed at compile time, and it continues to echo after each console entry until the model is deleted in the workspace.

```r
mod <- cmdstan_model(model_file, include_paths = dirname(data_file))
# Syntax error in 'C:/Users/<xxxx>/AppData/Local/Temp/1/RtmpGkRRHa/model_00252e81bad3382f6acdbe052a2f2912.stan', line 2, column 2, include error:
#    -------------------------------------------------
#      1:
#      2:    #include data.stan
#            ^
#      3:    parameters {
#      4:      vector[N] y;
#    -------------------------------------------------

# Could not find include file data.stan in specified include paths.

mod$sample(data = list(N = 1))
# All 4 chains finished successfully.
# Mean chain execution time: 0.1 seconds.
# Total execution time: 3.4 seconds.

#  variable  mean median   sd  mad    q5  q95 rhat ess_bulk ess_tail
#      lp__ -0.48  -0.21 0.69 0.29 -1.84 0.00 1.00     1501     2043
#      y[1] -0.04  -0.04 0.98 0.96 -1.68 1.60 1.00     1459     1758
# Syntax error in 'C:/Users/<xxxx>/AppData/Local/Temp/1/RtmpGkRRHa/model_00252e81bad3382f6acdbe052a2f2912.stan', line 2, column 2, include error:
#    -------------------------------------------------
#      1:
#      2:    #include data.stan
#            ^
#      3:    parameters {
#      4:      vector[N] y;
#    -------------------------------------------------

# Could not find include file data.stan in specified include paths.
```

**Comment by seabbs** [comment] 2023-04-25 20:40
Just noting that I see the same behaviour on Ubuntu 22.04.2 LTS and the latest version of `cmdstanr` and `cmdstan`. @beansrowning, myself and a few others have an issue discussing this here: https://github.com/epinowcast/epinowcast/issues/194 (though no particular new insights to add on what has already been discussed here).
