### ISSUE TITLE
log_prob function on cmdstanr output

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/cmdstanr#316] opened 2020-10-15 14:35 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to use bridgesampling with cmdstanr output, for this I would need to get the model's log posterior for a set of samples (https://github.com/quentingronau/bridgesampling/issues/27). For rstan this is available through the `log_prob` function.

**Describe the solution you'd like**
Get something similar to the output of `log_prob` function.

**Describe alternatives you've considered**
Or be able to use rstan `log_prob` function in a model compiled with cmdstanr

**Comment by jgabry** [comment] 2020-10-15 17:29
Hey Bruno, yeah this would be really nice but unfortunately this isn't something we can implement in CmdStanR until it's possible with CmdStan. The way RStan does it is by using Rcpp to call Stan C++ functions from R, but that's not possible with CmdStanR. Similarly, an equivalent to `rstan::expose_stan_functions()` doesn't exist in CmdStanR because it's not currently possible with CmdStan. 

That said, it's conceivable that CmdStan (or a new low-lever Stan interface) could offer something like this that CmdStanR could then expose. @mitzimorris @rok-cesnovar Any thoughts about this?

**Comment by bnicenboim** [comment] 2020-10-15 17:32
ok, I have to admit that I really don't understand how log_prob works. So this might be silly, but would it be possible to use log_prob on a model compiled with cmdstanr (somehow)?

**Comment by rok-cesnovar** [comment] 2020-10-15 17:44
> Similarly, an equivalent to `rstan::expose_stan_functions()` doesn't exist in CmdStanR because it's not currently possible with CmdStan.

This can now be done in cmdstan after https://github.com/stan-dev/stanc3/pull/524 (will be a part of 2.25). It's easy to do this with cmdstan and Rcpp, but I am not sure if we want to add Rcpp as a dependency to cmdstanr. I will look into if how maintainable a version without Rcpp would be (basically building an object file, not exe and `dyn.load` it in).

This could also be a separate package like "cmdstanr_functions", to keep cmdstanr "clean" of this more involved stuff. With stanc3 we could also pretty easily expose not only functions but also get gradients if that has a use-case.

> So this might be silly, but would it be possible to use log_prob on a model compiled with cmdstanr (somehow)?

It is definitely possible, it's more of a question of how to do it so that it does not become a support nightmare that rstan has recently become.

**Comment by jgabry** [comment] 2020-10-15 17:48
> > Similarly, an equivalent to `rstan::expose_stan_functions()` doesn't exist in CmdStanR because it's not currently possible with CmdStan.
> 
> This can now be done in cmdstan after [stan-dev/stanc3#524](https://github.com/stan-dev/stanc3/pull/524) (will be a part of 2.25).

Awesome!

> but I am not sure if we want to add Rcpp as a dependency to cmdstanr

Yeah I think we want to avoid that if possible. 

> This could also be a separate package like "cmdstanr_functions", to keep cmdstanr "clean" of this more involved stuff. With stanc3 we could also pretty easily expose not only functions but also get gradients if that has a use-case.

A separate package could be nice. I'd like to keep cmdstanr as "clean" as possible, like you say, but I definitely think this functionality is useful.

**Comment by rok-cesnovar** [comment] 2020-10-15 20:04
An example of how you can already do expose_stan_functions is given here: https://gist.github.com/rok-cesnovar/c91d631b66c1124ae7f221155f87516f#file-expose_cmdstanr_function

It does require cmdstan 2.25 RC

At the top is the function to expose and an example is given [below](https://gist.github.com/rok-cesnovar/c91d631b66c1124ae7f221155f87516f#file-expose_cmdstanr_function-L171)

It uses Rcpp and way too much hardcoded stuff, but I just wanted to prove that it can be done :) And you can use with 2.25.

**Comment by jgabry** [comment] 2020-10-15 20:14
Thanks Rok, very cool! We should definitely think about officially supporting this.

**Comment by jgabry** [comment] 2020-10-15 20:14
> Thanks Rok, very cool! We should definitely think about how to officially support this.

**Comment by jgabry** [comment] 2021-07-15 00:23
> Thanks Rok, very cool! We should definitely think about how to officially support this.

People have been asking about this, so just commenting here as a reminder to us to come back to this at some point. Previously we were thinking of doing this in a separate package to avoid a cmdstanr dependency on rcpp.

**Comment by mike-lawrence** [comment] 2021-07-15 14:37
I'm a bit confused; aren't the target/log-posterior values stored in the sampling output variable "lp_"? Or is the idea here that users want to evaluate the target at an arbitrary set of parameter values, not just those reflected in samples obtained by cmdstan's sampling run?

**Comment by rok-cesnovar** [comment] 2021-07-15 16:05
> Or is the idea here that users want to evaluate the target at an arbitrary set of parameter values, not just those reflected in samples obtained by cmdstan's sampling run

Yes, this. This is something that is doable with rstan.

**Comment by jgabry** [comment] 2021-07-15 18:24
And also the ability to expose Stan functions!

**Comment by bob-carpenter** [comment] 2022-09-07 21:54
Duplicate of #679

**Closed by bob-carpenter** 2022-09-07 21:54 UTC
Labels: feature
