### ISSUE TITLE
Converting saved cmdstanr fit object to stanfit

### ISSUE THREAD

**Issue by ssp3nc3r** [stan-dev/cmdstanr#279] opened 2020-08-16 22:36 UTC
In the current interface (0.1.1), the recommendation for converting from `cmdstanr` object to `rstan` object requires `rstan` to access temporary files directories, 

`stanfit <- rstan::read_stan_csv(fit$output_files())`

even after 

```
fit$save_object(file = "fit.RDS")

# can be read back in using readRDS
fit2 <- readRDS("fit.RDS")
```

It would be great to have a way to convert directly from the saved `cmdstanr` object, perhaps by having the method `$output_files()` to first look at its object for the information and, if not there, then try the temporary storage location?

**Comment by rok-cesnovar** [comment] 2020-08-17 09:30
The problem is that `rstan::read_stan_csv` requires actual Stan CSVs to work and if those do not exist we have two possible options: 

a) create the stanfit from the cmdstanr fit object
b) write the draws to a valid cmdstan CSV file


b) might be easier to implement but much less efficient

a) would remove the rstan requirement for creating a stanfit object, but would require creating everything in a stanfit object from fit$draws() and fit$metadata() and (probably) more.

**Comment by ssp3nc3r** [comment] 2020-08-17 12:51
It seems that adding a function to write the cmdstan csv would align more with the goals of the package, and provides a parallel function to `read_cmdstan_csv()`, and changing the documentation to reflect this use. If we find that the conversion ends up being an important part of workflow, then efficiency can be addressed.

**Comment by jgabry** [comment] 2020-08-17 15:51
Yeah starting with a function to write the csv sounds good to me.

**Comment by rok-cesnovar** [comment] 2021-05-25 10:42
Closing this as the solution to this is closing https://github.com/stan-dev/cmdstanr/issues/290

**Closed by rok-cesnovar** 2021-05-25 10:42 UTC
Labels: feature
