### ISSUE TITLE
Use variable as argument name consistently

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanr#228] opened 2020-06-27 12:01 UTC
`fit$print()` uses `variable` as an argument as does the posterior package. 

For `fit$draws()`, `read_cmdstan_csv` we use `variables = NULL`. That should be unified.

**Comment by jgabry** [comment] 2020-06-27 15:39
Where does`fit$print()` use `variable`? The definition is using plural `variables`:

https://github.com/stan-dev/cmdstanr/blob/012f97870822c5a3c9fba1f0a06adf9fefa7a4f0/R/fit.R#L75

But you're right that posterior is using the singular `variable` and we're using plural `variables`. I agree it would be best to unify that. 

I actually think `variables` makes more sense than the singular `variable` since selecting a single variable is really the special case and almost always we're dealing with multiple variables. @paul-buerkner What do you think? Are you open to us changing `variable` to `variables` in posterior? Because of partial argument matching I don't think it would actually break anything.

**Comment by rok-cesnovar** [comment] 2020-06-27 16:04
> Where does`fit$print()` use `variable`?

Sorry, not sure what I saw...
It's only posterior then. Still worth a thought to consolidate this. I am fine either way.

**Comment by jgabry** [comment] 2020-06-27 16:53
> Still worth a thought to consolidate this. I am fine either way.

I agree. Let’s see what Paul says about posterior and then we can decide if we’ll change it there or in cmdstanr.

**Comment by paul-buerkner** [comment] 2020-06-28 15:33
We have discussed this issue at some point in the context of `subset_draws` and agreed to use singular in a call back then. Here you can find the documented part of the discussion https://github.com/stan-dev/posterior/issues/7

I am happy to change my mind but I am not sure if we have any new arguments about this issue.

**Comment by jgabry** [comment] 2020-06-29 17:15
Thanks @paul-buerkner. Hmm, so I think the issue is that both make sense for different reasons:

- @paul-buerkner's comment at https://github.com/stan-dev/posterior/issues/7#issuecomment-546911471 is a good reason to use singular in posterior

but 

- when extracting variables from a fitted model object like in cmdstanr it makes much more sense to use the plural (if extracting K variables then for all K except K=1 the singular doesn't make sense)

So maybe there is no way to unify the names and have them always make sense. I guess we need to either 

(a) tolerate the different argument names (advantage is that both names make sense)

or 

(b) tolerate that the name won't always be the most sensible  (advantage is that the names are the same across packages)

I'm not yet sure if I think (a) or (b) is preferable. @rok-cesnovar and @paul-buerkner any further thoughts on this?

**Comment by rok-cesnovar** [comment] 2020-06-29 18:10
I would go for (a) then.

**Comment by paul-buerkner** [comment] 2020-06-29 18:28
(a) sounds good to me too.

**Comment by jgabry** [comment] 2020-06-29 20:09
Ok (a) it is! If users end up finding this very confusing I guess we can change it with deprecation, but I think people will be able to figure it out. Closing this now since option (a) doesn't require changing anything.

**Closed by jgabry** 2020-06-29 20:09 UTC
