### ISSUE TITLE
Error regarding dimensions after sampling.

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/cmdstanr#1050] opened 2024-12-12 20:09 UTC
**Describe the bug**

After the model completes sampling, the following error is raised.

```
Error in dim(x) <- c(dim(x), 1) : 
  dims [product 150] do not match the length of object [3]
```

**To Reproduce**

```stan
# Problematic Stan model.
parameters {
    vector [150] f;
}

model {
    f ~ normal(0, 1);
}
```

```R
> # Calling R code.
> library(cmdstanr)
> library(gptoolsStan)
> 
> cmdstan_model(
+   stan_file = "debug.stan"
+ )$sample(
+   data = list(n = 100, sigma = 1, length_scale = 0.1, period = 1),
+   chains = 1,
+   iter_warmup = 500,
+   iter_sampling = 50
+ )
Compiling Stan program...

[C++ compiler output]

Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
Error in dim(x) <- c(dim(x), 1) : 
  dims [product 150] do not match the length of object [3]
```

**Expected behavior**

The R code above returns a fit.

**Operating system**

```bash
$ uname -a
Linux 4dcbafc21a34 6.10.14-linuxkit #1 SMP Thu Oct 24 19:28:55 UTC 2024 aarch64 GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ R --version
R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-gnu (64-bit)
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
```

I am running this code in a Docker container with the above operating system. 

I do not get an error if I run the same code on the host machine with the following configuration.

```bash
$ uname -a
Darwin dhcp-10-250-31-164.harvard.edu 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 arm64
$ gcc --version
Apple clang version 16.0.0 (clang-1600.0.26.6)
Target: arm64-apple-darwin24.1.0
```

The output on the host machine is as follows.

```
Compiling Stan program...
Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
 variable   mean median   sd  mad     q5    q95 rhat ess_bulk ess_tail
     lp__ -75.81 -75.93 6.44 4.80 -88.77 -65.62 1.01       26       33
     f[1]   0.02   0.00 1.04 1.04  -1.53   1.48 1.25       71       31
     f[2]  -0.02  -0.09 0.91 0.81  -1.47   1.63 1.00       84       46
     f[3]   0.02  -0.10 1.02 1.11  -1.49   1.65 1.08       84       41
     f[4]  -0.09  -0.27 0.99 0.88  -1.45   1.61 1.02       84       62
     f[5]   0.10   0.34 1.13 1.01  -1.78   1.79 1.00       84       41
     f[6]  -0.13  -0.25 1.02 1.20  -1.61   1.64 1.00       84       37
     f[7]   0.01  -0.02 1.19 1.39  -1.88   1.86 1.00       84       46
     f[8]  -0.10  -0.25 1.12 1.27  -1.74   1.54 1.02       56       33
     f[9]  -0.21  -0.21 1.01 0.80  -2.02   1.90 1.00       84       40

 # showing 10 of 151 rows (change via 'max_rows' argument or 'cmdstanr_max_rows' option)
[...]
```

**CmdStanR version number (same in container and on host)**

```R
> packageVersion("cmdstanr")
[1] ‘0.8.1’
> cmdstan_version()
[1] "2.36.0"
```

**Additional context**

This problem arose in running the reproduction materials for our Gaussian process inference library after upgrading `cmdstan` and `cmdstanr` (cf. https://github.com/onnela-lab/gptools-reproduction-material/pull/4).

I searched GitHub for the code in the error message and found this section. Maybe it's relevant.

https://github.com/stan-dev/posterior/blob/79d4521b943e44f4ac31636c4488d9e2cfeac3ec/R/as_draws_array.R#L227-L239

**Comment by jgabry** [comment] 2024-12-12 21:28
Wow, that's very strange! I'm not able to reproduce this on either of my computers (although they're both Macs, just running different OS versions), which is going to make this tricky to debug. Does this happen with all models or just specific ones? 

> I searched GitHub for the code in the error message and found this section. Maybe it's relevant.

There's a decent chance that line in the posterior package is where the error is coming from, but, if so, I'm not sure why. 

Are you able to generate a `traceback()` so we can more about where the error is happening?

**Comment by tillahoffmann** [comment] 2024-12-12 21:41
Thanks for the fast reply! Here's the output of traceback. I have to admit I don't quite know how to interpret it.

```
12: as_array_matrix_list(x)
11: fun(x, ...)
10: as_draws.default(x)
9: as_draws(x)
8: as_draws_array.default(list(structure(list(treedepth__ = c(4L, 
   4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 3L, 4L, 4L, 3L, 4L, 
   4L, 4L, 4L, 3L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 3L, 4L, 4L, 4L, 
   4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 3L, 4L, 4L, 4L, 3L, 4L, 4L, 
   4L), divergent__ = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
   0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
   0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
   0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L), energy__ = c(160.001, 164.589, 
   149.329, 144.494, 140.444, 154.648, 147.947, 149.639, 141.597, 
   152.719, 143.787, 132.576, 148.491, 160.705, 165.513, 157.754, 
   146.246, 160.25, 160.585, 147.17, 146.789, 170.271, 161.011, 
   144.471, 151.956, 161.701, 165.189, 165.872, 154.899, 175.701, 
   156.912, 153.286, 132.044, 140.624, 136.904, 142.348, 130.973, 
   145.396, 143.553, 155.442, 150.118, 156.114, 156.571, 145.717, 
   146.662, 168.475, 166.723, 159.978, 158.845, 148.17)), row.names = c(NA, 
   -50L), class = "data.frame")))
7: (function (x, ...) 
   {
       UseMethod("as_draws_array")
   })(list(structure(list(treedepth__ = c(4L, 4L, 4L, 4L, 4L, 4L, 
   4L, 4L, 4L, 4L, 4L, 4L, 3L, 4L, 4L, 3L, 4L, 4L, 4L, 4L, 3L, 4L, 
   4L, 4L, 4L, 4L, 4L, 4L, 4L, 3L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 
   4L, 4L, 4L, 4L, 3L, 4L, 4L, 4L, 3L, 4L, 4L, 4L), divergent__ = c(0L, 
   0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
   0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
   0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
   0L), energy__ = c(160.001, 164.589, 149.329, 144.494, 140.444, 
   154.648, 147.947, 149.639, 141.597, 152.719, 143.787, 132.576, 
   148.491, 160.705, 165.513, 157.754, 146.246, 160.25, 160.585, 
   147.17, 146.789, 170.271, 161.011, 144.471, 151.956, 161.701, 
   165.189, 165.872, 154.899, 175.701, 156.912, 153.286, 132.044, 
   140.624, 136.904, 142.348, 130.973, 145.396, 143.553, 155.442, 
   150.118, 156.114, 156.571, 145.717, 146.662, 168.475, 166.723, 
   159.978, 158.845, 148.17)), row.names = c(NA, -50L), class = "data.frame")))
6: do.call(as_draws_format, list(post_warmup_sampler_diagnostics))
5: read_cmdstan_csv(files = self$output_files(include_failed = FALSE), 
       variables = variables, sampler_diagnostics = sampler_diagnostics, 
       format = format)
4: private$read_csv_(variables = "", sampler_diagnostics = convert_hmc_diagnostic_names(diagnostics))
3: initialize(...)
2: CmdStanMCMC$new(runset)
1: cmdstanr::cmdstan_model(stan_file = "debug.stan")$sample(data = list(n = 100, 
       sigma = 1, length_scale = 0.1, period = 1), chains = 1, iter_warmup = 500, 
       iter_sampling = 50)
```

**Comment by tillahoffmann** [comment] 2024-12-12 21:47
Was able to put together a reproducible example in Docker here: https://gist.github.com/tillahoffmann/ada92a970706c772c6ad2a477ec95fb2

**Comment by jgabry** [comment] 2024-12-12 22:08
Thanks, that's great. I'll build the image now, but unfortunately the rest of the day and the next week is insanely busy for me so I'm not sure when I'm going to have the time to dig into this if it doesn't turn out to be really simple . I'll try to make some time though! 

I think the traceback confirms your suspicion that the error is happening in those lines from posterior, but I'm not sure why yet.

**Comment by jgabry** [comment] 2024-12-12 22:16
Does this happen with all models or just certain ones?

**Comment by tillahoffmann** [comment] 2024-12-12 22:28
Sorry, forgot to address that earlier. I don't know if it happens for all models, but it seems to be an issue even for very simple ones like this one.

```stan
parameters {
    real f;
}

model {
    f ~ normal(0, 1);
}
```

The error messsage is as follows.

```
Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
Error in dim(x) <- c(dim(x), 1) : 
  dims [product 150] do not match the length of object [3]
```

I've just played around with this a bit more, and it only seems to happen if a single chain is run. It works fine for multiple chains.

**Comment by jgabry** [comment] 2024-12-13 15:53
Thanks for the extra details. This is indeed quite strange. 

> It looks like the number 150 is not related to the size of the vector but the number of samples. Specifically, the reported number is 3 * iter_sampling in some brief experiments.

The error seems to be happening when processing the data frame of sampler diagnostics, which your docker image helped me figure out. The data frame has `iter_sampling` rows and 3 columns (`treedepth__`, `divergent__`, `energy__`). If you set `diagnostics = NULL` when calling the `sample` method there's no error, but then if you call `fit$sampler_diagnostics()` after sampling you'll still get the error. But that's as far as I've gotten so far. What I really don't understand is why this would only be reproducible on Docker (as far as we know). Or have you been able to reproduce it outside of Docker?

**Comment by tillahoffmann** [comment] 2024-12-13 16:54
It's weird with the Docker image. Maybe it's related to being on Linux rather than macOS?

**Comment by jgabry** [comment] 2024-12-13 17:08
This keeps getting stranger. So the function in the posterior package that you found (https://github.com/stan-dev/posterior/blob/79d4521b943e44f4ac31636c4488d9e2cfeac3ec/R/as_draws_array.R#L227-L239) is indeed where the error is happening. On my computer the input to that function is a list of matrices (one per chain). In the Docker image the input to that function is a list of data frames (one per chain, if chains > 1) and a single data frame if chains = 1.

**Comment by jgabry** [comment] 2024-12-13 17:37
Continues to get stranger. I just opened up a fresh terminal inside the docker image, started a new R session, and ran your model with no error!

**Comment by jgabry** [comment] 2024-12-13 17:53
@tillahoffmann @paul-buerkner I think I may have narrowed this down to an issue in the development version of posterior on GitHub vs the CRAN version of posterior. In Docker, if I install posterior from CRAN I don't get the error. If I install it from GitHub I do get the error. @tillahoffmann can you replicate that? I still can't replicate it locally, but on Docker this seems to be replicable for me. 

I'm wondering if it has to do with https://github.com/stan-dev/posterior/commit/79d4521b943e44f4ac31636c4488d9e2cfeac3ec, but not sure.

**Comment by jgabry** [comment] 2024-12-13 18:04
This makes no sense! These are both run from terminals opened inside Docker. In one case I don't get the error at all, regardless of posterior version. In the other case I get the error with both versions of posterior! 

### Here no error

```
R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> remotes::install_cran("posterior")
Installing 1 packages: posterior

The downloaded binary packages are in
/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T//RtmpdAhAGS/downloaded_packages
> packageVersion("posterior")
[1] '1.6.0'
> stan_file <- cmdstanr::write_stan_file(
+   "
+ parameters {
+     vector [150] f;
+ }
+ 
+ model {
+     f ~ normal(0, 1);
+ }
+ "
+ )
> fit <- cmdstanr::cmdstan_model(
+   stan_file = stan_file
+ )$sample(
+   data = list(n = 100),
+   chains = 1,
+   iter_warmup = 500,
+   iter_sampling = 50
+ )
Compiling Stan program...
Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.


> remotes::install_github("stan-dev/posterior")
Using GitHub PAT from the git credential store.
Downloading GitHub repo stan-dev/posterior@HEAD
-- R CMD build ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
v  checking for file '/private/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T/RtmpdAhAGS/remotes13d7644dc3cdc/stan-dev-posterior-79d4521/DESCRIPTION' ...
-  preparing 'posterior':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts (594ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
   Omitted 'LazyData' from DESCRIPTION
-  building 'posterior_1.6.0.9000.tar.gz'
   
* installing *source* package 'posterior' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (posterior)
Adding 'posterior_1.6.0.9000.tgz' to the cache
> packageVersion("posterior")
[1] '1.6.0.9000'
> stan_file <- cmdstanr::write_stan_file(
+   "
+ parameters {
+     vector [150] f;
+ }
+ 
+ model {
+     f ~ normal(0, 1);
+ }
+ "
+ )
> fit <- cmdstanr::cmdstan_model(
+   stan_file = stan_file
+ )$sample(
+   data = list(n = 100),
+   chains = 1,
+   iter_warmup = 500,
+   iter_sampling = 50
+ )
Model executable is up to date!
Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
> packageVersion("posterior")
[1] '1.6.0.9000'
> 
```

### Here always error

```
R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> remotes::install_github("stan-dev/posterior", force = TRUE)
Using GitHub PAT from the git credential store.
Downloading GitHub repo stan-dev/posterior@HEAD
-- R CMD build ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
v  checking for file '/private/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T/RtmpH3O2co/remotes13f01494be17d/stan-dev-posterior-79d4521/DESCRIPTION' ...
-  preparing 'posterior':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts (419ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
   Omitted 'LazyData' from DESCRIPTION
-  building 'posterior_1.6.0.9000.tar.gz'
   
* installing *source* package 'posterior' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (posterior)
Adding 'posterior_1.6.0.9000.tgz' to the cache
> packageVersion("posterior")
[1] '1.6.0.9000'
> stan_file <- cmdstanr::write_stan_file(
+   "
+ parameters {
+     vector [150] f;
+ }
+ 
+ model {
+     f ~ normal(0, 1);
+ }
+ "
+ )
> fit <- cmdstanr::cmdstan_model(
+   stan_file = stan_file
+ )$sample(
+   data = list(n = 100),
+   chains = 1,
+   iter_warmup = 500,
+   iter_sampling = 50
+ )
Compiling Stan program...
Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
Error in dim(x) <- c(dim(x), 1) : 
  dims [product 150] do not match the length of object [3]


> remotes::install_cran("posterior")
Installing 1 packages: posterior

The downloaded binary packages are in
/var/folders/s0/zfzm55px2nd2v__zlw5xfj2h0000gn/T//RtmpH3O2co/downloaded_packages
> packageVersion("posterior")
[1] '1.6.0.9000'
> stan_file <- cmdstanr::write_stan_file(
+   "
+ parameters {
+     vector [150] f;
+ }
+ 
+ model {
+     f ~ normal(0, 1);
+ }
+ "
+ )
> fit <- cmdstanr::cmdstan_model(
+   stan_file = stan_file
+ )$sample(
+   data = list(n = 100),
+   chains = 1,
+   iter_warmup = 500,
+   iter_sampling = 50
+ )
Model executable is up to date!
Running MCMC with 1 chain...

Chain 1 Iteration:   1 / 550 [  0%]  (Warmup) 
Chain 1 Iteration: 100 / 550 [ 18%]  (Warmup) 
Chain 1 Iteration: 200 / 550 [ 36%]  (Warmup) 
Chain 1 Iteration: 300 / 550 [ 54%]  (Warmup) 
Chain 1 Iteration: 400 / 550 [ 72%]  (Warmup) 
Chain 1 Iteration: 500 / 550 [ 90%]  (Warmup) 
Chain 1 Iteration: 501 / 550 [ 91%]  (Sampling) 
Chain 1 Iteration: 550 / 550 [100%]  (Sampling) 
Chain 1 finished in 0.0 seconds.
Error in dim(x) <- c(dim(x), 1) : 
  dims [product 150] do not match the length of object [3]
> 
```

**Comment by jgabry** [comment] 2024-12-13 18:23
I think the problem is this commit to posterior: https://github.com/stan-dev/posterior/commit/79d4521b943e44f4ac31636c4488d9e2cfeac3ec

**Comment by jgabry** [comment] 2024-12-13 18:30
Ok @tillahoffmann check out https://github.com/stan-dev/posterior/issues/386. Can you replicate that?

**Comment by tillahoffmann** [comment] 2024-12-13 21:22
Thank you for the thorough investigation. Yes, I can replicate the behavior from stan-dev/posterior#386.

**Comment by jgabry** [comment] 2024-12-13 21:34
Ok great, thanks for checking and for reporting this.

**Comment by jgabry** [comment] 2024-12-17 16:39
We reverted the problematic commit in posterior, so I'm going to close this

**Comment by jgabry** [comment] 2024-12-17 16:40
Thanks again for reporting this and creating the reproducible example in Docker, that was really helpful.

**Closed by jgabry** 2024-12-17 16:39 UTC
Labels: bug

**Comment by tillahoffmann** [comment] 2024-12-17 16:43
Great, thank you for digging into it and fixing it so quickly! I probably shouldn't be running single chains anyway. 😬
