### ISSUE TITLE
Bug in mod$generated_quantities()$draws(format='draws_list')?

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanr#546] opened 2021-09-07 12:18 UTC
I'm running `cmdstanr_0.4.0.9000` & `posterior_1.0.1`, and when I run generate quantities on a model then draws, all is well, but any subsequent calls to draws yields an error, the precise wording of which is dependent on how I call draws. 

[Here's Stan code](https://github.com/stan-dev/cmdstanr/files/7121400/pvgp_generate.txt) (as a txt file; github won't let me upload .stan) defining a model for generating data, and here's some R code showing the various failure states:
```R
n = 2^7 #bigger n will take longer; 2^7 takes about 90s on a reasonably modern cpu
x = 1:n #x can be anything (doesn't have to be on a grid)
generate_mod = cmdstanr::cmdstan_model('pvgp_generate.stan')
data = list(
	n = n
	, x = x
	, pvn_ = .2
	, lengthscale_ = .1*diff(range(x))
	, sample_pvn = F
	, sample_lengthscale = F
)

generated = generate_mod$generate_quantities(
	data = data
	, fitted_params = posterior::as_draws_array(data.frame(dummy=0))
)
generated$draws() #runs fine
generated$draws() #runs fine
generated$draws('f') #runs fine
generated$draws() #runs fine
generated$draws('f') #runs fine

#now to break it
generated$draws(format='draws_list') #Error: The following variables are missing in the draws object: ...
generated$draws() #Error: 'iteration_ids' of bound objects do not match.

# generate again to make it all better
generated = generate_mod$generate_quantities(
	data = data
	, fitted_params = posterior::as_draws_array(data.frame(dummy=0))
)
generated$draws('f') #runs fine
generated$draws(format='draws_list') #Error: 'iteration_ids' of bound objects do not match.
generated$draws() #Error: 'iteration_ids' of bound objects do not match.
generated$draws('f') #Error: 'iteration_ids' of bound objects do not match.

# generate again to make it all better
generated = generate_mod$generate_quantities(
	data = data
	, fitted_params = posterior::as_draws_array(data.frame(dummy=0))
)
generated$draws(format='draws_list') #runs fine
generated$draws() #runs fine
generated$draws('f') #runs fine
generated$draws(format='draws_list') #Error: The following variables are missing in the draws object: ...

# generate again to make it all better
generated = generate_mod$generate_quantities(
	data = data
	, fitted_params = posterior::as_draws_array(data.frame(dummy=0))
)
generated$draws(format='draws_list') #runs fine
generated$draws(format='draws_list') #Error in .subset2(x, i, exact = exact) : subscript out of bounds

# generate again to make it all better
generated = generate_mod$generate_quantities(
	data = data
	, fitted_params = posterior::as_draws_array(data.frame(dummy=0))
)
generated$draws('f',format='draws_list') #runs fine
generated$draws('y',format='draws_list') #runs fine
generated$draws('f') #runs fine
generated$draws('f',format='draws_list') #Error: The following variables are missing in the draws object:
generated$draws('f') #Error: 'iteration_ids' of bound objects do not match.
```

**Comment by rok-cesnovar** [comment] 2021-09-07 19:02
Thanks @mike-lawrence for reporting! I have to dig a bit deeper, not 100% sure what is up right now. Here is what I know so far:

```r
library(cmdstanr)

n = 2^7
x = 1:n

generate_mod = cmdstanr::cmdstan_model('pvgp_generate.stan')

data = list( n = n, x = x, pvn_ = .2, lengthscale_ = .1*diff(range(x)), sample_pvn = F, sample_lengthscale = F)

generated = generate_mod$generate_quantities(data = data, fitted_params = posterior::as_draws_array(data.frame(dummy=0)))

d_arr <- generated$draws()

print(d_arr)
posterior::as_draws_list(d_arr)
```

So the problem is the following:

```r
> print(d_arr)
# A draws_array: 1 iterations, 1 chains, and 518 variables
, , variable = y_[1]

         chain
iteration   1
        1 2.3

, , variable = y_[2]

         chain
iteration   1
        1 1.3

, , variable = y_[3]

         chain
iteration   1
        1 1.9

, , variable = y_[4]

         chain
iteration   1
        1 1.5

# ... with 514 more variables
> posterior::as_draws_list(d_arr)
# A draws_list: 518 iterations, 1 chains, and 1 variables

[chain = 1]
$value
 [1] 2.311 1.256 1.945 1.529 1.529 1.937 1.055 0.754 1.911 0.028

# ... with 508 more iterations
```

So this returns a single variable termed `value`. This is obviously incorrect. This seems like a posterior issue? But not 100% just  at the moment.

**Comment by rok-cesnovar** [comment] 2021-09-10 09:57
This is a posterior issue with handling a single iteration. As there is nothing to do on the cmdstanr end, I am going to close this. I opened a posterior issue here: https://github.com/stan-dev/posterior/issues/203

**Closed by rok-cesnovar** 2021-09-10 09:57 UTC
Labels: bug

**Comment by rok-cesnovar** [comment] 2021-09-10 10:33
Actually, seems that this has been addressed in the last posterior release. both your and mine example work now.
