### ISSUE TITLE
Paths with spaces in them

### ISSUE THREAD

**Issue by hhau** [stan-dev/cmdstanr#75] opened 2019-11-11 14:28 UTC
Compilation method doesn't handle file paths with spaces in them:

```
[14:18:31] hhau:Desktop $ tree
.
├── dir\ withaspace
│   └── ex-three-gaussians-melded-joint.stan
└── ex-three-gaussians-melded-joint.stan

1 directory, 2 files
[14:18:32] hhau:Desktop $ Rscript -e "invisible(cmdstanr::cmdstan_model('ex-three-gaussians-melded-joint.stan'))"               
Compiling Stan program...
[14:18:45] hhau:Desktop $ Rscript -e "invisible(cmdstanr::cmdstan_model('dir withaspace/ex-three-gaussians-melded-joint.stan'))"     
Compiling Stan program...
Error in processx::run(command = make_cmd(), args = exe, wd = cmdstan_path(),  : 
  System command error
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> <Anonymous> -> <Anonymous> -> throw
Execution halted
[14:18:50] hhau:Desktop $ tree
.
├── dir\ withaspace
│   └── ex-three-gaussians-melded-joint.stan
├── ex-three-gaussians-melded-joint
├── ex-three-gaussians-melded-joint.hpp
├── ex-three-gaussians-melded-joint.o
└── ex-three-gaussians-melded-joint.stan

1 directory, 5 files
```

I can't quite figure out the structure of the `CmdStanModel` object to find the culprit - I think that calls to `system` need appropriate extra quotation a la: https://github.com/stan-dev/rstantools/pull/44/commits/504f0d691d50776a614b89fd3270e83fd69b7db5

**Comment by rok-cesnovar** [comment] 2019-11-11 15:24
Thanks for reporting. 

I am almost certain its a lack of quotation marks as you mention. We probably have the same issue for all path handling, not just compiling.

**Comment by mitzimorris** [comment] 2019-11-11 16:20
FWIW, paths with spaces are problematic for CmdStanPy - will be fixed by
https://github.com/stan-dev/cmdstanpy/pull/168https://github.com/stan-dev/cmdstanpy/pull/168

**Comment by jgabry** [comment] 2019-11-12 00:11
@hhau Thanks for reporting this. @rok-cesnovar  I think `repair_path()` is called for all paths at some point so hopefully we can just deal with this once in `repair_path()` and all cases will be fixed.

**Comment by jgabry** [comment] 2019-11-12 02:52
On second thought, we might need to slightly refactor how we're handling paths in order to make sure that quotes aren't added twice if `repair_path()` is called multiple times on a path (that's currently possible given that `repair_path()` is used inside `cmdstan_ext()` and inside `abolute_path()` and probably other places).

**Comment by rok-cesnovar** [comment] 2019-12-08 11:34
I thought about this one more thoroughly and looked at what cmdstanpy does.

First thing to note is that cmdstan will not work with spaces in the path.

What cmdstanpy does to circumvent this is copy the stan file to a tmp folder (that obviously has no spaces) and compile it there. I think this was the way cmdstanpy operated before this spaces fix.

So in order to this fix we need to go this route also. Which means we need to check timestamp on stan files etc. Any thoughts?

**Comment by mitzimorris** [comment] 2019-12-08 16:32
C++ has no restrictions on filenames - whatever the OS allows is legal.
as Roc notes, we're using gnuMake to transpile/compile/link, so the problem is underlyingly a makefile issue.

CmdStanPy and CmdStanR control the call to `make`.  for the CmdStan user, they'd need to figure out how to call `make` from the command line with the filename properly escaped, otherwise the shell's tokenizer will split on spaces by default.

this issue was filed and closed as "wontfix": https://github.com/stan-dev/cmdstan/issues/774

there are two options:

- continue to go with CmdStan restrictions on Stan program filenames
- fix makefiles

if we fix the makefiles, would we need to fix anything in CmdStan C++ code?

**Comment by mitzimorris** [comment] 2019-12-08 16:38
(thought this was filed against CmdStan - apologies if this seems slightly off-topic).

**Closed** 2020-03-11 18:58 UTC
Labels: bug
