### ISSUE TITLE
Length-one vectors are incorrectly read as single values

### ISSUE THREAD

**Issue by CharnelMouse** [stan-dev/cmdstanr#513] opened 2021-06-17 11:51 UTC
My model takes a few vector inputs, where the length is given as an earlier input.
However, if that length happens to be one, the input is, I think, erroneously taken as a single integer, causing an error.

Simple data block example:

```{r}
data {
  int<lower=0> len;
  int vals[len];
}
```

Error:

`Chain 1 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=vals; dims declared=(1); dims found=() (in 'path', line 3, ...`

This occurs using both JSON and a `stan_rdump`. I'm using the same model on multiple sets of data, where only some have length-one lengths, so I'd rather not do a model rewrite if I can avoid it.

Operating system: Windows 10
Version: 2.27.0

**Comment by mike-lawrence** [comment] 2021-06-17 12:14
Encountered the same thing myself just recently. Thanks for taking the time to submit as an issue.

**Comment by jgabry** [comment] 2021-06-17 15:45
Thanks for the bug report. Do you have a small self contained example I can use to trigger the error? Thanks!

**Comment by CharnelMouse** [comment] 2021-06-17 16:36
Sure!

```{r}
library(cmdstanr)

writeLines(
"data {
  int<lower=0> len;
  int<lower=1,upper=2> vals[len];
}
",
"tmp.stan"
)

len <- 1L
vals <- 2L
rstan::stan_rdump(c("len", "vals"), "tmp.rdump")
dat <- list(
  len = len,
  vals = vals
)
write_stan_json(dat, "tmp.json")

model <- cmdstan_model("tmp.stan")
model$sample(data = "tmp.rdump")
model$sample(data = "tmp.json")
```

**Comment by jgabry** [comment] 2021-06-17 16:47
Thanks. I think the solution (at least for now) is to use `as.array(vals)`, which will work regardless of the number of elements: 

```r
dat <- list(
  len = len,
  vals = as.array(vals)
)
model$sample(data = dat)  # or using json or rdump
```

Also, totally unrelated to the issue, but you can use the convenience function `write_stan_file()`, which defaults to using a temporary file, and returns the path to the file:

```r
file <- write_stan_file("
data {
  int<lower=0> len;
  int vals[len];
}
")
model <- cmdstan_model(file)
```

What you used is totally fine, just wanted to let you know about `write_stan_file()` in case you hadn't seen it.

**Comment by CharnelMouse** [comment] 2021-06-17 17:18
Using arrays makes it work for now, thanks!

**Comment by jgabry** [comment] 2021-06-17 20:21
I thought a bit more about this and I don't think there's a good solution other than having the user use `as.array()` themselves in R. 

The issue is that Stan differentiates between `int vals` and `int vals[1]`. In the first case in R we need `vals = integer` but in the second case we need `vals = as.array(integer)`. CmdStanR doesn't know what's in the Stan program (it just outsources that to Stan's parser and compiler) so it can't know whether `as.array` is required or not. 

I'm going to close this, but if anyone has an idea for dealing with this in CmdStanR that I overlooked then we can definitely reopen this.

**Comment by jgabry** [comment] 2021-06-17 20:29
Actually I'm going to reopen this temporarily because we can at least add something to doc about this.

**Comment by rok-cesnovar** [comment] 2021-06-17 20:37
Actually we can check whether its an array or not with 2.27 now. I am working on adding the basic functionality for $variables() this week.

**Comment by jgabry** [comment] 2021-06-17 21:09
Oh I forgot about that new addition as of 2.27, that's great!

**Comment by rok-cesnovar** [comment] 2021-07-19 09:24
A branch for this is ready, just needs #519 to be merged first.

**Closed** 2021-08-23 15:53 UTC
Labels: bug
