### ISSUE TITLE
passing a matrix as data for a 2d array of integers gets flattened

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/cmdstanr#606] opened 2021-12-02 09:17 UTC
**Describe the bug**
If the model has an array of integers of two dimension in the data section, it gets flattened to a one dimensional array.

**To Reproduce**
```
code <- '
data{
int m[2,2];
}
parameters{
real x;
}
model {
x ~ std_normal();
}
'

mod <- cmdstan_model(write_stan_file(code))
d <- list(m = matrix(1, nrow =2, ncol=2))
mod$sample(data = d)
```
I would expect this to work (or at least that stan would complain that m contains real numbers and not integers)

But this happens:
```
## Chain 2 Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=m; dims declared=(2,2); dims found=(4) (in '/tmp/RtmpmiXaZI/model-105bf65057fc2e.stan', line 3, column 0 to column 11)
## Warning: Chain 2 finished unexpectedly!
```

**Expected behavior**

If the matrix is made out of integers, this works though
```
d <- list(m = matrix(1L, nrow =2, ncol=2))
mod$sample(data = d)
```

**Versions**
```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS
cmdstanr_0.4.0.9000
```

**Comment by bnicenboim** [comment] 2021-12-02 09:22
I would bet that at some point cmdstanr does `as.integer(m)`, if m is a matrix of non-integers. Since this flattens a matrix. But I couldn't find that in cmdstanr code.

**Comment by rok-cesnovar** [comment] 2021-12-02 09:29
Yes, we do that in order to differentiate from `int` and an `int [1]`, which R does not differentiate, but Stan does. It should not obviously flatten this.

**Comment by rok-cesnovar** [comment] 2021-12-02 09:47
This actually runs fine for me on the latest Github development version. This was fixed in https://github.com/stan-dev/cmdstanr/pull/563 I am guessing you have the development version right from that period. 

We know we haven't been very good with upgrading the actual package's version :( Sorry for the inconvenience Bruno and thanks for always detailed and reproducible issue reports. If you confirm that upgrading fixes this issue, please close.

**Comment by bnicenboim** [comment] 2021-12-02 10:00
ok, I installed from the repo again and  it works, even though the version number didn't change...

**Comment by rok-cesnovar** [comment] 2021-12-02 10:01
Yeah, because we haven't updated it, always anticipating that the 1.0 release is just around the corner, yet it still hasn't happened. 

I will go ahead and bump the version today, there really is no excuse for this.

**Comment by rok-cesnovar** [comment] 2021-12-02 10:04
PR done: https://github.com/stan-dev/cmdstanr/pull/607

Will close this then! Sorry again.

**Closed by rok-cesnovar** 2021-12-02 10:04 UTC
Labels: bug
